export const tutorsData = [
  {
    _id: 1,
    name: 'Stanley Kubrick',
    email: 'Kubrick@gmail.com',
    description:
      'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Aliquid accusamus omnis voluptatum voluptate illum laborum vel. Modi, qui nemo, porro nesciunt beatae, aperiam nulla nam provident sapiente neque cum cumque?',
    password: '',
    profession: 'mathematician',
    schedule: 'mornings from 10am to 12pm ',
    profile_photo: '',
    rating: 5,
    category: 'Math',
  },
  {
    _id: 2,
    name: 'Ciro Guerra',
    email: 'Ciro@gmail.com',
    description:
      'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Aliquid accusamus omnis voluptatum voluptate illum laborum vel. Modi, qui nemo, porro nesciunt beatae, aperiam nulla nam provident sapiente neque cum cumque?',
    password: '',
    profession: 'mathematician',
    schedule: 'mornings from 10am to 12pm ',
    profile_photo: '',
    rating: 5,
    category: 'Math',
  },
  {
    _id: 3,
    name: 'Andrei Tarkovski',
    email: 'Andrei@gmail.com',
    description:
      'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Aliquid accusamus omnis voluptatum voluptate illum laborum vel. Modi, qui nemo, porro nesciunt beatae, aperiam nulla nam provident sapiente neque cum cumque?',
    password: '',
    profession: 'mathematician',
    schedule: 'mornings from 10am to 12pm ',
    profile_photo: '',
    rating: 5,
    category: 'Math',
  },
  {
    _id: 4,
    name: 'Charlie Kaufman',
    email: 'Charlie@gmail.com',
    description:
      'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Aliquid accusamus omnis voluptatum voluptate illum laborum vel. Modi, qui nemo, porro nesciunt beatae, aperiam nulla nam provident sapiente neque cum cumque?',
    password: '',
    profession: 'mathematician',
    schedule: 'mornings from 10am to 12pm ',
    profile_photo: '',
    rating: 5,
    category: 'Math',
  },
  {
    _id: 1,
    name: 'Stanley Kubrick',
    email: 'Kubrick@gmail.com',
    description:
      'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Aliquid accusamus omnis voluptatum voluptate illum laborum vel. Modi, qui nemo, porro nesciunt beatae, aperiam nulla nam provident sapiente neque cum cumque?',
    password: '',
    profession: 'mathematician',
    schedule: 'mornings from 10am to 12pm ',
    profile_photo: '',
    rating: 5,
    category: 'Philosophy',
  },
  {
    _id: 2,
    name: 'Ciro Guerra',
    email: 'Ciro@gmail.com',
    description:
      'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Aliquid accusamus omnis voluptatum voluptate illum laborum vel. Modi, qui nemo, porro nesciunt beatae, aperiam nulla nam provident sapiente neque cum cumque?',
    password: '',
    profession: 'mathematician',
    schedule: 'mornings from 10am to 12pm ',
    profile_photo: '',
    rating: 5,
    category: 'Philosophy',
  },
  {
    _id: 3,
    name: 'Andrei Tarkovski',
    email: 'Andrei@gmail.com',
    description:
      'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Aliquid accusamus omnis voluptatum voluptate illum laborum vel. Modi, qui nemo, porro nesciunt beatae, aperiam nulla nam provident sapiente neque cum cumque?',
    password: '',
    profession: 'mathematician',
    schedule: 'mornings from 10am to 12pm ',
    profile_photo: '',
    rating: 5,
    category: 'Philosophy',
  },
  {
    _id: 4,
    name: 'Charlie Kaufman',
    email: 'Charlie@gmail.com',
    description:
      'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Aliquid accusamus omnis voluptatum voluptate illum laborum vel. Modi, qui nemo, porro nesciunt beatae, aperiam nulla nam provident sapiente neque cum cumque?',
    password: '',
    profession: 'mathematician',
    schedule: 'mornings from 10am to 12pm ',
    profile_photo: '',
    rating: 5,
    category: 'Philosophy',
  },
  {
    _id: 1,
    name: 'Stanley Kubrick',
    email: 'Kubrick@gmail.com',
    description:
      'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Aliquid accusamus omnis voluptatum voluptate illum laborum vel. Modi, qui nemo, porro nesciunt beatae, aperiam nulla nam provident sapiente neque cum cumque?',
    password: '',
    profession: 'mathematician',
    schedule: 'mornings from 10am to 12pm ',
    profile_photo: '',
    rating: 5,
    category: 'Math',
  },
  {
    _id: 2,
    name: 'Ciro Guerra',
    email: 'Ciro@gmail.com',
    description:
      'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Aliquid accusamus omnis voluptatum voluptate illum laborum vel. Modi, qui nemo, porro nesciunt beatae, aperiam nulla nam provident sapiente neque cum cumque?',
    password: '',
    profession: 'mathematician',
    schedule: 'mornings from 10am to 12pm ',
    profile_photo: '',
    rating: 5,
    category: 'Math',
  },
  {
    _id: 3,
    name: 'Andrei Tarkovski',
    email: 'Andrei@gmail.com',
    description:
      'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Aliquid accusamus omnis voluptatum voluptate illum laborum vel. Modi, qui nemo, porro nesciunt beatae, aperiam nulla nam provident sapiente neque cum cumque?',
    password: '',
    profession: 'mathematician',
    schedule: 'mornings from 10am to 12pm ',
    profile_photo: '',
    rating: 5,
    category: 'Math',
  },
  {
    _id: 4,
    name: 'Charlie Kaufman',
    email: 'Charlie@gmail.com',
    description:
      'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Aliquid accusamus omnis voluptatum voluptate illum laborum vel. Modi, qui nemo, porro nesciunt beatae, aperiam nulla nam provident sapiente neque cum cumque?',
    password: '',
    profession: 'mathematician',
    schedule: 'mornings from 10am to 12pm ',
    profile_photo: '',
    rating: 5,
    category: 'Math',
  },
  {
    _id: 1,
    name: 'Stanley Kubrick',
    email: 'Kubrick@gmail.com',
    description:
      'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Aliquid accusamus omnis voluptatum voluptate illum laborum vel. Modi, qui nemo, porro nesciunt beatae, aperiam nulla nam provident sapiente neque cum cumque?',
    password: '',
    profession: 'mathematician',
    schedule: 'mornings from 10am to 12pm ',
    profile_photo: '',
    rating: 5,
    category: 'Computer Science',
  },
  {
    _id: 2,
    name: 'Ciro Guerra',
    email: 'Ciro@gmail.com',
    description:
      'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Aliquid accusamus omnis voluptatum voluptate illum laborum vel. Modi, qui nemo, porro nesciunt beatae, aperiam nulla nam provident sapiente neque cum cumque?',
    password: '',
    profession: 'mathematician',
    schedule: 'mornings from 10am to 12pm ',
    profile_photo: '',
    rating: 5,
    category: 'Computer Science',
  },
  {
    _id: 3,
    name: 'Andrei Tarkovski',
    email: 'Andrei@gmail.com',
    description:
      'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Aliquid accusamus omnis voluptatum voluptate illum laborum vel. Modi, qui nemo, porro nesciunt beatae, aperiam nulla nam provident sapiente neque cum cumque?',
    password: '',
    profession: 'mathematician',
    schedule: 'mornings from 10am to 12pm ',
    profile_photo: '',
    rating: 5,
    category: 'Computer Science',
  },
  {
    _id: 4,
    name: 'Charlie Kaufman',
    email: 'Charlie@gmail.com',
    description:
      'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Aliquid accusamus omnis voluptatum voluptate illum laborum vel. Modi, qui nemo, porro nesciunt beatae, aperiam nulla nam provident sapiente neque cum cumque?',
    password: '',
    profession: 'mathematician',
    schedule: 'mornings from 10am to 12pm ',
    profile_photo: '',
    rating: 5,
    category: 'Computer Science',
  },
  {
    _id: 1,
    name: 'Stanley Kubrick',
    email: 'Kubrick@gmail.com',
    description:
      'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Aliquid accusamus omnis voluptatum voluptate illum laborum vel. Modi, qui nemo, porro nesciunt beatae, aperiam nulla nam provident sapiente neque cum cumque?',
    password: '',
    profession: 'mathematician',
    schedule: 'mornings from 10am to 12pm ',
    profile_photo: '',
    rating: 5,
    category: 'Biology',
  },
  {
    _id: 2,
    name: 'Ciro Guerra',
    email: 'Ciro@gmail.com',
    description:
      'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Aliquid accusamus omnis voluptatum voluptate illum laborum vel. Modi, qui nemo, porro nesciunt beatae, aperiam nulla nam provident sapiente neque cum cumque?',
    password: '',
    profession: 'mathematician',
    schedule: 'mornings from 10am to 12pm ',
    profile_photo: '',
    rating: 5,
    category: 'Biology',
  },
  {
    _id: 3,
    name: 'Andrei Tarkovski',
    email: 'Andrei@gmail.com',
    description:
      'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Aliquid accusamus omnis voluptatum voluptate illum laborum vel. Modi, qui nemo, porro nesciunt beatae, aperiam nulla nam provident sapiente neque cum cumque?',
    password: '',
    profession: 'mathematician',
    schedule: 'mornings from 10am to 12pm ',
    profile_photo: '',
    rating: 5,
    category: 'Biology',
  },
  {
    _id: 4,
    name: 'Charlie Kaufman',
    email: 'Charlie@gmail.com',
    description:
      'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Aliquid accusamus omnis voluptatum voluptate illum laborum vel. Modi, qui nemo, porro nesciunt beatae, aperiam nulla nam provident sapiente neque cum cumque?',
    password: '',
    profession: 'mathematician',
    schedule: 'mornings from 10am to 12pm ',
    profile_photo: '',
    rating: 5,
    category: 'Biology',
  },
  {
    _id: 1,
    name: 'Stanley Kubrick',
    email: 'Kubrick@gmail.com',
    description:
      'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Aliquid accusamus omnis voluptatum voluptate illum laborum vel. Modi, qui nemo, porro nesciunt beatae, aperiam nulla nam provident sapiente neque cum cumque?',
    password: '',
    profession: 'mathematician',
    schedule: 'mornings from 10am to 12pm ',
    profile_photo: '',
    rating: 5,
    category: 'Design',
  },
  {
    _id: 2,
    name: 'Ciro Guerra',
    email: 'Ciro@gmail.com',
    description:
      'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Aliquid accusamus omnis voluptatum voluptate illum laborum vel. Modi, qui nemo, porro nesciunt beatae, aperiam nulla nam provident sapiente neque cum cumque?',
    password: '',
    profession: 'mathematician',
    schedule: 'mornings from 10am to 12pm ',
    profile_photo: '',
    rating: 5,
    category: 'Design',
  },
  {
    _id: 3,
    name: 'Andrei Tarkovski',
    email: 'Andrei@gmail.com',
    description:
      'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Aliquid accusamus omnis voluptatum voluptate illum laborum vel. Modi, qui nemo, porro nesciunt beatae, aperiam nulla nam provident sapiente neque cum cumque?',
    password: '',
    profession: 'mathematician',
    schedule: 'mornings from 10am to 12pm ',
    profile_photo: '',
    rating: 5,
    category: 'Design',
  },
  {
    _id: 4,
    name: 'Charlie Kaufman',
    email: 'Charlie@gmail.com',
    description:
      'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Aliquid accusamus omnis voluptatum voluptate illum laborum vel. Modi, qui nemo, porro nesciunt beatae, aperiam nulla nam provident sapiente neque cum cumque?',
    password: '',
    profession: 'mathematician',
    schedule: 'mornings from 10am to 12pm ',
    profile_photo: '',
    rating: 5,
    category: 'Design',
  },
  {
    _id: 1,
    name: 'Stanley Kubrick',
    email: 'Kubrick@gmail.com',
    description:
      'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Aliquid accusamus omnis voluptatum voluptate illum laborum vel. Modi, qui nemo, porro nesciunt beatae, aperiam nulla nam provident sapiente neque cum cumque?',
    password: '',
    profession: 'mathematician',
    schedule: 'mornings from 10am to 12pm ',
    profile_photo: '',
    rating: 5,
    category: 'Art',
  },
  {
    _id: 2,
    name: 'Ciro Guerra',
    email: 'Ciro@gmail.com',
    description:
      'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Aliquid accusamus omnis voluptatum voluptate illum laborum vel. Modi, qui nemo, porro nesciunt beatae, aperiam nulla nam provident sapiente neque cum cumque?',
    password: '',
    profession: 'mathematician',
    schedule: 'mornings from 10am to 12pm ',
    profile_photo: '',
    rating: 5,
    category: 'Art',
  },
  {
    _id: 3,
    name: 'Andrei Tarkovski',
    email: 'Andrei@gmail.com',
    description:
      'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Aliquid accusamus omnis voluptatum voluptate illum laborum vel. Modi, qui nemo, porro nesciunt beatae, aperiam nulla nam provident sapiente neque cum cumque?',
    password: '',
    profession: 'mathematician',
    schedule: 'mornings from 10am to 12pm ',
    profile_photo: '',
    rating: 5,
    category: 'Art',
  },
  {
    _id: 4,
    name: 'Charlie Kaufman',
    email: 'Charlie@gmail.com',
    description:
      'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Aliquid accusamus omnis voluptatum voluptate illum laborum vel. Modi, qui nemo, porro nesciunt beatae, aperiam nulla nam provident sapiente neque cum cumque?',
    password: '',
    profession: 'mathematician',
    schedule: 'mornings from 10am to 12pm ',
    profile_photo: '',
    rating: 5,
    category: 'Art',
  },
  {
    _id: 1,
    name: 'Stanley Kubrick',
    email: 'Kubrick@gmail.com',
    description:
      'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Aliquid accusamus omnis voluptatum voluptate illum laborum vel. Modi, qui nemo, porro nesciunt beatae, aperiam nulla nam provident sapiente neque cum cumque?',
    password: '',
    profession: 'mathematician',
    schedule: 'mornings from 10am to 12pm ',
    profile_photo: '',
    rating: 5,
    category: 'Engineering',
  },
  {
    _id: 2,
    name: 'Ciro Guerra',
    email: 'Ciro@gmail.com',
    description:
      'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Aliquid accusamus omnis voluptatum voluptate illum laborum vel. Modi, qui nemo, porro nesciunt beatae, aperiam nulla nam provident sapiente neque cum cumque?',
    password: '',
    profession: 'mathematician',
    schedule: 'mornings from 10am to 12pm ',
    profile_photo: '',
    rating: 5,
    category: 'Engineering',
  },
  {
    _id: 3,
    name: 'Andrei Tarkovski',
    email: 'Andrei@gmail.com',
    description:
      'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Aliquid accusamus omnis voluptatum voluptate illum laborum vel. Modi, qui nemo, porro nesciunt beatae, aperiam nulla nam provident sapiente neque cum cumque?',
    password: '',
    profession: 'mathematician',
    schedule: 'mornings from 10am to 12pm ',
    profile_photo: '',
    rating: 5,
    category: 'Engineering',
  },
  {
    _id: 4,
    name: 'Charlie Kaufman',
    email: 'Charlie@gmail.com',
    description:
      'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Aliquid accusamus omnis voluptatum voluptate illum laborum vel. Modi, qui nemo, porro nesciunt beatae, aperiam nulla nam provident sapiente neque cum cumque?',
    password: '',
    profession: 'mathematician',
    schedule: 'mornings from 10am to 12pm ',
    profile_photo: '',
    rating: 5,
    category: 'Engineering',
  },
  {
    _id: 1,
    name: 'Stanley Kubrick',
    email: 'Kubrick@gmail.com',
    description:
      'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Aliquid accusamus omnis voluptatum voluptate illum laborum vel. Modi, qui nemo, porro nesciunt beatae, aperiam nulla nam provident sapiente neque cum cumque?',
    password: '',
    profession: 'mathematician',
    schedule: 'mornings from 10am to 12pm ',
    profile_photo: '',
    rating: 5,
    category: 'Chemistry',
  },
  {
    _id: 2,
    name: 'Ciro Guerra',
    email: 'Ciro@gmail.com',
    description:
      'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Aliquid accusamus omnis voluptatum voluptate illum laborum vel. Modi, qui nemo, porro nesciunt beatae, aperiam nulla nam provident sapiente neque cum cumque?',
    password: '',
    profession: 'mathematician',
    schedule: 'mornings from 10am to 12pm ',
    profile_photo: '',
    rating: 5,
    category: 'Chemistry',
  },
  {
    _id: 3,
    name: 'Andrei Tarkovski',
    email: 'Andrei@gmail.com',
    description:
      'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Aliquid accusamus omnis voluptatum voluptate illum laborum vel. Modi, qui nemo, porro nesciunt beatae, aperiam nulla nam provident sapiente neque cum cumque?',
    password: '',
    profession: 'mathematician',
    schedule: 'mornings from 10am to 12pm ',
    profile_photo: '',
    rating: 5,
    category: 'Chemistry',
  },
  {
    _id: 4,
    name: 'Charlie Kaufman',
    email: 'Charlie@gmail.com',
    description:
      'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Aliquid accusamus omnis voluptatum voluptate illum laborum vel. Modi, qui nemo, porro nesciunt beatae, aperiam nulla nam provident sapiente neque cum cumque?',
    password: '',
    profession: 'mathematician',
    schedule: 'mornings from 10am to 12pm ',
    profile_photo: '',
    rating: 5,
    category: 'Chemistry',
  },
];
