export const categoriesData = [
  {
    _id: 1,
    subject: 'Math',
    focus: 'math',
    profession: 'chemical engineer',
    tutorId: '',
  },
  {
    _id: 2,
    subject: 'Biology',
    focus: 'math',
    profession: 'chemical engineer',
    tutorId: '',
  },
  {
    _id: 3,
    subject: 'Computer Science',
    focus: 'math',
    profession: 'chemical engineer',
    tutorId: '',
  },
  {
    _id: 4,
    subject: 'Philosophy',
    focus: 'math',
    profession: 'chemical engineer',
    tutorId: '',
  },
  {
    _id: 5,
    subject: 'Art',
    focus: 'math',
    profession: 'chemical engineer',
    tutorId: '',
  },
  {
    _id: 6,
    subject: 'Design',
    focus: 'math',
    profession: 'chemical engineer',
    tutorId: '',
  },
  {
    _id: 7,
    subject: 'Engineering',
    focus: 'math',
    profession: 'chemical engineer',
    tutorId: '',
  },
  {
    _id: 8,
    subject: 'Chemistry',
    focus: 'math',
    profession: 'chemical engineer',
    tutorId: '',
  },
  {
    _id: 9,
    subject: 'Anthropology',
    focus: 'math',
    profession: 'chemical engineer',
    tutorId: '',
  },
  {
    _id: 10,
    subject: 'Marketing',
    focus: 'math',
    profession: 'chemical engineer',
    tutorId: '',
  },
  {
    _id: 11,
    subject: 'Architecture',
    focus: 'math',
    profession: 'chemical engineer',
    tutorId: '',
  },
];
